#if !canImport(ObjectiveC)
import XCTest

extension AmazonRawTranscriptTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__AmazonRawTranscriptTests = [
        ("test_parseAmazonTranscribeJSONFile", test_parseAmazonTranscribeJSONFile),
    ]
}

extension AmazonTranscriptTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__AmazonTranscriptTests = [
        ("test_makeTranscriptFromTranscriptFile", test_makeTranscriptFromTranscriptFile),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(AmazonRawTranscriptTests.__allTests__AmazonRawTranscriptTests),
        testCase(AmazonTranscriptTests.__allTests__AmazonTranscriptTests),
    ]
}
#endif
